name: qr_code_getx
version: 1.0.0+1
publish_to: none
description: Login and QR Code Apps
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
